// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryLayer;

#nullable disable

namespace RepositoryLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240116232242_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DomainLayer.models.Default_Slice_Values", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Condition")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reasons")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Sanitation_price")
                        .HasMaxLength(7)
                        .HasColumnType("real");

                    b.Property<float>("Water_Price")
                        .HasMaxLength(7)
                        .HasColumnType("real");

                    b.HasKey("Code");

                    b.ToTable("Tbl_Default_Slice_Values");
                });

            modelBuilder.Entity("DomainLayer.models.Invoices", b =>
                {
                    b.Property<string>("NO_Invoice")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int>("Amount_Consumption_Amount")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<float>("Consumption_Value")
                        .HasMaxLength(11)
                        .HasColumnType("real");

                    b.Property<int>("Current_Consumption_Amount")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FK_Real_Estate_Types_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("FK_Subscriber_No")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FK_Subscription_No_sp_Date")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("FK_Subscription_No_sp_id")
                        .HasColumnType("int");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Is_There_Sanitation")
                        .HasColumnType("bit");

                    b.Property<int>("Previous_Consumption_Amount")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("Reasons")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Service_Free")
                        .HasMaxLength(11)
                        .HasColumnType("real");

                    b.Property<float>("Tax_Rate")
                        .HasMaxLength(11)
                        .HasColumnType("real");

                    b.Property<float>("Tax_Value")
                        .HasMaxLength(11)
                        .HasColumnType("real");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<float>("Total_Bill")
                        .HasMaxLength(11)
                        .HasColumnType("real");

                    b.Property<float>("Total_Invoice")
                        .HasMaxLength(11)
                        .HasColumnType("real");

                    b.Property<float>("Wastewater_Consumption_Value")
                        .HasMaxLength(11)
                        .HasColumnType("real");

                    b.Property<string>("year")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("NO_Invoice");

                    b.ToTable("Tbl_Invoices");
                });

            modelBuilder.Entity("DomainLayer.models.Real_Estate_Types", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Reasons")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Code");

                    b.ToTable("Tbl_Real_Estate_Types");
                });

            modelBuilder.Entity("DomainLayer.models.Subscriber_File", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Reasons")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Subscriber_File");
                });

            modelBuilder.Entity("DomainLayer.models.Subscription_File", b =>
                {
                    b.Property<string>("NO_Subscription")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("FK_Real_Estate_Types_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("FK_Subscriber_No")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Is_There_Sanitation")
                        .HasColumnType("bit");

                    b.Property<int>("Last_Reading_Meter")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("Reasons")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Unit_No")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.HasKey("NO_Subscription");

                    b.ToTable("Tbl_Subscription_File");
                });
#pragma warning restore 612, 618
        }
    }
}
